### ISSUE TITLE
Add credit to readme with link to original repo

### ISSUE THREAD

**Issue by polarathene** [payday-restoration/BigLobby3#5]
Please add to your Github README.md a credit link to the [original repo](https://github.com/polarathene/biglobby) since you did not fork my repo. It's a great improvement and I understand if you want to maintain your own repo instead of contribute back to original.

---

Also note, this link https://modworkshop.net/mydownloads.php?action=view_down&did=21582 states 128 player support. To my knowledge this won't work unless duplicate character support is properly done. I was working on it when developing biglobby but did not get to finish. You need to go through the games codebase and track how it manages and refers/looksup players, sometimes it's by player model/character, so you need to make changes to have it refer to a player by their character and say a suffix like `_peer_id` such that instead of looking up by `dallas` it might look up `dallas_3`, then a function that will when requesting the dallas character asset/model trim the suffix from `dallas_3` to `dallas`.

It's not an easy find/replace task, you have to go through alot of methods and trace how the devs decided to do the lookups(several approaches iirc). If you get that right, then can support duplicate characters without crash/bugs(eg two dallas, one of them picks up equipment or some other event, perhaps go into custody, and it instead apply to the first dallas).

**Comment by Iamgoofball** [comment]
My apologies, I just got my computer set back up and functional, was remodeling.

I apologize deeply for forgetting to provide credit here on the repo, I forgot to copypaste it over to here from the modworkshop description when I set that up.

I'll see if I can turn this into a fork of the original repo, I'd rather maintain it myself under the organization so that I can directly push fixes/API changes, and if you don't mind, please send me your email so I can add you to the organization as well for push rights. Same with @steam-test1

**Comment by Iamgoofball** [comment]
Fixed in https://github.com/payday-restoration/BigLobby3/commit/7495443d0251cad9a195c1ca39d1dee45ef2c237

**Comment by polarathene** [comment]
@Iamgoofball It's alright :) Thanks for adding the credit link. You don't need to fork the repo this is fine, as long as it links back to my original work.

I'm not 100% sure as my knowledge on licenses is a bit weak but I've been informed that you're meant to include [my MIT license](https://github.com/polarathene/biglobby/blob/master/LICENSE) with the code as well. I'm not sure how that works with you licensing your code under a different license. Personally I'm not too fussed, as long as there is linked attribution which you've since done. Thanks :)

I don't need push rights, I don't see myself having time to any serious work on the mod anymore, I might get around to releasing the rest of my payday2 mod codes including partial work on biglobby features. If I come back to the game perhaps I'll send you a PR :P 

All the best with this mod! It should be much easier to maintain with the new injection approach! :D

**Comment by ZNixian** [comment]
@polarathene The rule with the MIT license is that you're allowed to do anything you want, so long you include the original license. This does include re-licensing - you're requiring people to comply with the AGPLv3, but the MIT license imposes no restrictions on doing so.

You should read [the GNU's page on license compatibility and relicensing](https://www.gnu.org/licenses/license-compatibility.html) - it's fairly short, and gives a good overview of this rather complicated issue.
