### ISSUE TITLE
Found the mistake from you mod.txt

### ISSUE THREAD

**Issue by Jacky10X** [payday-restoration/BigLobby3#6]
From mod.txt
`		{
			"hook_id": "lib/network/base/handlers/packetnetworkhandler",
			"script_path": "lua/lib/network/base/handlers/_packetnetworkhandler.lua"
		},
		{
			"hook_id": "lib/network/base/handlers/basenetworkhandler",
			"script_path": "lua/lib/network/base/handlers/_basenetworkhandler.lua"
		}`
You are using those filed that doesn't exist....
Maybe you should better remove them(but it doesn't effect anything so that why i call this is mistake)

**Comment by Iamgoofball** [comment]
Thanks
